/*
 * This source file was generated by the Gradle 'init' task
 */
package org.byorkt

class ByoRkt {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(ByoRkt().greeting)
}
