/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.byorkt.ByoRkt
import kotlin.test.Test
import kotlin.test.assertNotNull

class ByoRktTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = ByoRkt()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
